### PR TITLE
feat: improve the homepage design

### PR DESCRIPTION
**Pull request by jamwag**
- Move inline css colors to tailwind.config.js
- Add global padding inside Section.svelte
- Fix padding on smaller devices using media queries

 ### TODOS for future issues

- Add a responsive styling to the home page
- Fetch data from CMS and calendar

### CODE REVIEW

**Comment by Flosi23** [comment]
Ok, everything fine for me. The white space at the bottom of the hero is reserved for the nav, i suppose ?

Unbenannt

Now you only have to merge the latest changes from master into this branch and resolve all merge conflicts. Then it can be merged with @GitGangGuy approval.

**Comment by Lacrimus** [comment]
Any reason for Prettier failing in CI?

**Review by Flosi23 — APPROVED** [review]

**Comment by GitGangGuy** [comment]
The `index.html` file has to be split back into components, and we should address the removal of media queries in a seperate issue (I think media queries are a bad thing because they aren't fluid/cause breakpoints, which is something we initially tried to avoid by using viewport-dependent units - also, those media queries are currently using `px`, which is an unreliable metric since it depends on the users screen resolution). If somebody could fix the shortcomings that would be great. LGTM.

**Review by GitGangGuy — APPROVED** [review]
TODO: Remove media queries, split `index.html`, switch to standardized color palette in `tailwind.config.js`

**Pull request merged**
